# -*- coding: utf-8 -*-
"""Task3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GGus3nYAUoOE-09kPrThhjX62vfAWd2N
"""

'''
Write a Python program that accepts the user's first and last name and prints them in reverse order with a space between them.
'''
print("Please enter the first name")
first_name=input()
print("Please enter the last name")
last_name=input()

print(last_name+" "+first_name)