# -*- coding: utf-8 -*-
"""Task12.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GGus3nYAUoOE-09kPrThhjX62vfAWd2N
"""

'''
Write a Python program to get the volume of a sphere with radius six.
'''
import math
r=6
pi=math.pi
value=float(4/3)*pi*r**3
print(value)