# -*- coding: utf-8 -*-
"""Task11.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GGus3nYAUoOE-09kPrThhjX62vfAWd2N
"""

'''
Write a Python program to calculate the number of days between two dates.
'''
from datetime import date
f_date=date(2022,8,9)
l_date=date(2022,8,20)
diff=l_date-f_date
print(diff)