# -*- coding: utf-8 -*-
"""Task4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GGus3nYAUoOE-09kPrThhjX62vfAWd2N
"""

'''
Write a Python program that accepts a sequence of comma-separated numbers from the user and generates a list and a tuple of those numbers.
Sample data : 3, 5, 7, 23
'''
print("Please enter the number with comma")
data=input()
list=data.split(',')
converted_list=[int(i) for i in list] # converting list data
tuple_data=tuple(converted_list)
print(converted_list)
print(tuple_data)