# -*- coding: utf-8 -*-
"""Task10.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GGus3nYAUoOE-09kPrThhjX62vfAWd2N
"""

pip install calender

'''
Write a Python program to print the following 'here document'.
Sample string:
a string that you "don't" have to escape
This
is a ....... multi-line
heredoc string --------> example
'''
print("""
a string that you "don't" have to escape
This
is a  ....... multi-line
heredoc string --------> example
""")