# -*- coding: utf-8 -*-
"""Task7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GGus3nYAUoOE-09kPrThhjX62vfAWd2N
"""

'''
Write a Python program that accepts an integer (n) and computes the value of n+nn+nnn.
Sample value of n is 5
Expected Result : 615
'''
print("Please enter the value of n")
n=input()
temp=int(n)
sum=0
for i in range(3):
  print(temp)
  sum=sum+temp
  temp=temp*10+int(n)
print(sum)