# -*- coding: utf-8 -*-
"""Task13.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GGus3nYAUoOE-09kPrThhjX62vfAWd2N
"""

'''
Write a Python program to calculate the difference between a given number and 17.
If the number is greater than 17, return twice the absolute difference.
'''
import math
print("Please enter the number")
number=int(input())
if(number<17):
  res=number-17
  res=abs(res)
  print(res)
else:
  res=number-17
  res=res*2
  print(res)