# -*- coding: utf-8 -*-
"""Task9.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GGus3nYAUoOE-09kPrThhjX62vfAWd2N
"""

pip install calender

'''
Write a Python program that prints the calendar for a given month and year.
'''
import calendar
date=9
month=8
year=1992

print(calendar.month(year,month,date))